test_size: 0.2
random_state: 3
features:
  - engines
  - passenger_capacity
  - crew
  - company_rating
  - review_scores_rating
  - d_check_complete
  - moon_clearance_complete
  - iata_approved
categorical_features:
  - d_check_complete
  - moon_clearance_complete
  - iata_approved
model_params:
  hyper_parameters:
    max_depth: 7
    n_estimators: 30
    random_state: 555
