version: '3.3'
services:
  proto-api:
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        S3_BUCKET: $S3_BUCKET
        S3_BUCKET_KEY: $S3_BUCKET_KEY
        MODEL_PATH: $MODEL_PATH
    volumes:
      - ./models:/models
      - ./app:/app
    ports:
      - "50051:50051"
    tty: true