version: "3.8"
services:
  kedro-example:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 9999:8888
    volumes:
      - ~/projects/kedro-sample:/kedro-sample
      - ~/data:/data
    tty: true
